# Generated by Django 6.0.2 on 2026-02-25 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('effective_date', models.DateField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='laws.law')),
            ],
        ),
    ]
