# Generated by Django 6.0.2 on 2026-02-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_lawversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawversion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='law_pdfs/'),
        ),
    ]
