# Generated by Django 6.0.2 on 2026-02-25 09:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0005_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='lawversion',
            options={'ordering': ['-effective_date']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='law',
        ),
        migrations.RemoveField(
            model_name='law',
            name='content',
        ),
        migrations.RemoveField(
            model_name='law',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='lawversion',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='lawversion',
            name='version_number',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'law')},
        ),
    ]
