# Generated by Django 6.0.2 on 2026-02-25 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0006_alter_activitylog_options_alter_law_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='law',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lawversion',
            options={},
        ),
        migrations.AddField(
            model_name='law',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Батлагдсан огноо'),
        ),
        migrations.AddField(
            model_name='law',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='law',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Хүчин төгөлдөр болсон огноо'),
        ),
        migrations.AddField(
            model_name='law',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Баталсан байгууллага'),
        ),
        migrations.AddField(
            model_name='law',
            name='law_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Хуулийн дугаар'),
        ),
        migrations.AddField(
            model_name='law',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='law_pdfs/'),
        ),
        migrations.AddField(
            model_name='law',
            name='status',
            field=models.CharField(choices=[('active', 'Хүчинтэй'), ('inactive', 'Хүчингүй'), ('draft', 'Төсөл')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='law',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Товч тайлбар'),
        ),
        migrations.AddField(
            model_name='lawversion',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='law',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
